version: '2'
services:
  lb:
    image: rancher/lb-service-haproxy:${RANCHER_LB_HAPROXY_VER}
    ports:
      - ${LB_PORT}:${LB_PORT}/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: tier=private
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
  contentful-nginx-cache:
    image: ${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}:${BUILDKITE_BUILD_NUMBER}
    environment:
      HOST_TO_CACHE: 'cdn.contentful.com'
      CACHE_TTL: '30s'
      CACHE_LOCK_TIMEOUT: '1s'
    labels:
      io.rancher.container.pull_image: 'always'
      io.rancher.scheduler.affinity:host_label: 'tier=private'
