steps:
  - name: ":docker: build + push + rmi"
    env:
      HTTP_PROXY: "http://proxy.ops.scentregroup.io:3128"
    commands:
      - docker build --build-arg http_proxy=\${HTTP_PROXY} --build-arg https_proxy=\${HTTP_PROXY} -t ${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}:${BUILDKITE_BUILD_NUMBER} -t ${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}:latest ./
      - docker push ${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}:${BUILDKITE_BUILD_NUMBER}
      - docker push ${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}:latest
      - docker rmi ${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}:${BUILDKITE_BUILD_NUMBER}

  - wait

  - name: ":rancher: [dev] deploy"
    command: stack_deploy
    env:
      LB_PORT: 8012
      STACK_ENV: dev
      STACK_NAME: ${BUILDKITE_PIPELINE_SLUG}
      SCALE: 2

  - block: ':rancher: [stg] initiate deploy'

  - name: ":rancher: [stg] deploy"
    command: stack_deploy
    env:
      LB_PORT: 8012
      STACK_ENV: stg
      STACK_NAME: ${BUILDKITE_PIPELINE_SLUG}
      SCALE: 4

  - block: ':rancher: [prd] initiate deploy'

  - name: ":rancher: [prd] deploy"
    command: stack_deploy
    env:
      LB_PORT: 8012
      STACK_ENV: prd
      STACK_NAME: ${BUILDKITE_PIPELINE_SLUG}
      SCALE: 4
